import type { WordCategoryId } from "../shared/event.contracts";

export interface WordCategory {
  id: WordCategoryId;
  label: string;
  words: string[];
}

export const WORD_CATEGORIES: WordCategory[] = [
  {
    id: "clash_royale",
    label: "Clash Royale Cards",
    words: [
      "archers",
      "arrows",
      "baby dragon",
      "bandit",
      "barbarian barrel",
      "barbarians",
      "bats",
      "battle ram",
      "bowler",
      "cannon",
      "dark prince",
      "electro wizard",
      "elite barbarians",
      "fireball",
      "freeze",
      "giant",
      "goblin barrel",
      "goblin gang",
      "goblins",
      "golem",
      "graveyard",
      "hog rider",
      "ice golem",
      "ice spirit",
      "ice wizard",
      "inferno dragon",
      "inferno tower",
      "knight",
      "lightning",
      "log",
      "lumberjack",
      "mega knight",
      "mega minion",
      "miner",
      "mini pekka",
      "minion horde",
      "minions",
      "mortar",
      "musketeer",
      "pekka",
      "poison",
      "prince",
      "princess",
      "rage",
      "rocket",
      "royal ghost",
      "royal giant",
      "skeleton army",
      "skeletons",
      "sparky",
      "tesla",
      "tombstone",
      "valkyrie",
      "witch",
      "wizard",
      "x bow",
      "zap"
    ]
  },
  {
    id: "animals",
    label: "Animals",
    words: [
      "dog",
      "cat",
      "lion",
      "tiger",
      "elephant",
      "giraffe",
      "zebra",
      "monkey",
      "panda",
      "kangaroo",
      "dolphin",
      "whale",
      "shark",
      "eagle",
      "owl",
      "fox",
      "wolf",
      "bear",
      "rabbit",
      "turtle",
      "snake",
      "crocodile",
      "hippo",
      "rhino"
    ]
  },
  {
    id: "countries",
    label: "Countries",
    words: [
      "argentina",
      "brazil",
      "canada",
      "china",
      "egypt",
      "france",
      "germany",
      "india",
      "indonesia",
      "italy",
      "japan",
      "mexico",
      "nigeria",
      "pakistan",
      "portugal",
      "russia",
      "south korea",
      "united kingdom",
      "united states"
    ]
  }
];

